version: '3.3'

services:
  composer:
    image: composer:1.8
    volumes:
      - .:/app
    environment:
      - COMPOSER_AUTH=${COMPOSER_AUTH}

  runner:
    image: php:7-cli-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: ['php', 'run.php']
